### ISSUE TITLE
ExternalScripts not loading script when doing client navigation

### ISSUE THREAD

**Issue by jacargentina** [sergiodxa/remix-utils#73] opened 2022-04-28 17:19 UTC
### Describe the bug

ExternalScripts seems to not load on client -side navigation

### Your Example Website or App

https://github.com/jacargentina/my-remix

### Steps to Reproduce the Bug or Issue

1. remix dev
2. clic on "Recaptcha"
3. clic the Test button
4. The alert shows `typeof window.grecaptcha` which is undefined

### Expected behavior

4. The alert must show 'object' as the recaptcha script is loaded & run

### Platform

- OS: macOS
- Browser: Chrome
- Version: current

**Comment by ElouadiAbdelati** [comment] 2022-08-01 21:56
same problem !

**Comment by seblaz** [comment] 2022-08-26 23:26
Hi, any idea why this is happening? It seems that the script elements are correctly inserted in the DOM but for some reason they are now beeing executed

**Comment by sergiodxa** [comment] 2022-12-13 04:14
I'm honestly not sure what's happening here yet, from what I see the scripts are rendered but browsers are ignoring them.

**Comment by brandonpittman** [comment] 2023-01-13 05:56
Probably an ad blocker is stopping them.

**Comment by tpiros** [comment] 2023-02-24 14:29
I have a similar issue with another third party script - no ad blockers are in place fyi.

**Comment by kroofy** [comment] 2023-02-24 19:36
Changing it to return `<script>`s in server mode and creating script elements in client mode, works for me when navigating.

Not sure it is a good way though.

Relevant bit here:

https://github.com/sergiodxa/remix-utils/blob/7ca64ecadc6a9ce09f455f08f512b46f7718d6df/src/react/external-scripts.tsx#L50
```tsx
  // ...
  const isClient = typeof document !== "undefined";

  if (isClient) {
    {
      scripts.forEach((props) => {
        let scriptElement = document.createElement("script");

        scriptElement.setAttribute("src", props.src);

        document.body.appendChild(scriptElement);
      });
    }
  }

  return (
    <>
      {scripts.map((props) => {
        let rel = props.noModule ? "modulepreload" : "preload";
        let as = !props.noModule ? "script" : undefined;
        return (
          <link
            key={props.src}
            rel={rel}
            href={props.src}
            as={as}
            crossOrigin={props.crossOrigin}
            integrity={props.integrity}
            referrerPolicy={props.referrerPolicy}
          />
        );
      })}

      {!isClient &&
        scripts.map((props) => {
          return <script {...props} key={props.src} />;
        })}
    </>
  );
```

**Comment by brandonpittman** [comment] 2023-04-18 06:53
> I'm honestly not sure what's happening here yet, from what I see the scripts are rendered but browsers are ignoring them.

I can confirm this. The browser shows it in the HTML but it's not showing up under the Sources tab in Chrome.

**Comment by jdnichollsc** [comment] 2023-07-18 05:02
Getting same error while injecting external scripts using ClientOnly, e.g:
```
<ClientOnly fallback={null}>
  {() => (
    <script
      suppressHydrationWarning
      type="text/javascript"
      id="hs-script-loader"
      async
      defer
      crossOrigin="anonymous"
      src="https://js-na1.hs-scripts.com/....js"
    />
  )}
</ClientOnly>
```

**Comment by jdnichollsc** [comment] 2023-07-18 05:58
Ok, I created a custom component and it's working for loading these external scripts:
```
import { ComponentPropsWithoutRef, useEffect } from 'react';

export type BodyScriptsProps = ComponentPropsWithoutRef<'script'>;

export const BodyScript: React.FC<BodyScriptsProps> = (props) => {
  useEffect(() => {
    if (!props.src) return;
    const script = document.createElement('script');
    script.src = props.src;
    const keys = Object.keys(props);
    for (let index = 0; index < keys.length; index++) {
      const key = keys[index];
      // @ts-ignore
      script[key] = props[key];
    }
    document.body.appendChild(script);
    return () => {
      document.body.removeChild(script);
    };
  }, [props.src])

  return null;
}
```
let me know what you think! <3

**Comment by sergiodxa** [comment] 2023-10-06 09:13
This should have been fixed in v7, the ExternalScripts component now uses document.createElement and body.append to insert the script tags after hydration.

**Closed by sergiodxa** 2023-10-06 09:13 UTC
Labels: bug
